config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy #Just so you can log out directly via the address bar
  end

  controller :users do
    get 'register' => :new
  end

  resources :users, :only => [:new, :create]
  resources :orders, :only => [:new, :create]
  resources :line_items, :only => [:new, :create, :destroy]
  resources :baskets, :only => [:new, :show, :create, :destroy]
  resources :wines, :only => [:index,:show]

  root to: 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

  #Order is a simple Activerecord class used to wrap user and basket information
  #Validations based off examples given in workshops
  has_many :line_items
  validates :name, :address, :email, presence: true
  validates_format_of :email,
                      with: /\A([\w\.\-\+]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      message: 'Bad email address format'
  validates_format_of :name,
                      with: /\A([a-zA-Z0-9'\s]*{2,})\z/i,
                      message: 'Bad name format'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]




  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    # we authorize first so there'll always be a user in the session... heh..
    populate_placeholder_values
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    # todo refactor this method... pls!
    @order = Order.new(order_params)

    basket = @basket
    # we only want to process baskets that contain wines
    if basket.line_items.length > 0
      move_line_items_to_order basket, @order
    else
      redirect_to basket_path basket.id, notice: 'Invalid basket'
      return
    end

    #We marshal the order data into a hash and get all the suppliers
    # OrderService.marshal_order_to_hash(@order)
    OrderService.do_order(@order)

    # Baskets that have been processed successfully need to be destroyed and removed
    # from the session hash
    respond_to do |format|
      if @order.save
        Basket.destroy(session[:basket_id])
        session[:basket_id] = nil
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:name, :email, :address)
  end

  #we want to populate some values from the current user into the order
  # we don't want to do this in the view so it's here
  def populate_placeholder_values
    current_user = User.find_by_id session[:user_id]
    @order.name = current_user.name
    @order.email = current_user.email
    @order.address = current_user.address
  end


  #persist the line_items in the order so basket can be destroyed
  def move_line_items_to_order basket ,order
    basket.line_items.each do |item|
      item.basket_id = nil #prevent cascade delete
      order.line_items  << item
    end
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name , class:'form-control' %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email,class:'form-control' %>
    </div>

    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address, class:'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Place Order', id:'place_order',class:'btn btn-default'%>
      <%= link_to 'Continue Shopping', wines_path, class:'btn btn-default' %>
    </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Basket</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.basket %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
<h1>Checkout</h1>

<%= render 'form' %>

</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Basket:</strong>
  <%= @order.basket %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>