config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy #Just so you can log out directly via the address bar
  end

  controller :users do
    get 'register' => :new
  end

  resources :users, :only => [:new, :create]
  resources :orders, :only => [:new, :create]
  resources :line_items, :only => [:new, :create, :destroy]
  resources :baskets, :only => [:new, :show, :create, :destroy]
  resources :wines, :only => [:index,:show]

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sig 2 Comparisons</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container" id="top-bar-container">
  <div class="row">
    <div class="col-md-12">
      <h1>Sig2 Wine Comparison!
        	<span class="pull-right">

               <%= form_tag  wines_path , :method=>:get, class:'form-inline', id:'wine-search-form' do %>
                   <%= search_field_tag :search, params[:search], placeholder: 'Search wines', class:'form-control' %>
                <%= submit_tag 'Search', class:'btn btn-default' ,id:'wine-search-submit' %>
               <% end %>
          </span>
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
        <span class="pull-left">
           <span id="miniBasket">
             <% if @basket %>
               <%= render @basket %>
              <% end %>
             </span>
        </span>
      <div id="login" class="pull-right">
        <% if is_logged_in? %>
            <p>LOGGED IN </p>
            <p id="topbar_username">Hi, <%= get_session_user_name %></p>
            <%= link_to 'Log out',  logout_path, id:'logout_button', class:'btn btn-default'%>
        <% else %>
            <p>Not logged in</p>
            <%= link_to 'Log in', login_path,id:'login_button', class:'btn btn-default'%>
        <% end %>
      </div>
    </div>
  </div>

</div>


<div id="content" class="container">
  <%= yield %>
</div>
</body>
</html>